/**
 * UI Performance PoC — WireMock-backed login
 *
 * Prerequisites (run once before k6):
 *   npx tsx perf-tests/setup.ts
 *
 * Run:
 *   k6 run --env TARGET_URL=http://localhost:3000 perf-tests/UiPerformancePocTestPrzemek.js
 *
 * How login works:
 *   The UI redirects to WireMock /authorize?login_hint={nhsNumber}.
 *   WireMock immediately 302s back to /callback?code={perVuCode}&state=...
 *   The login Lambda exchanges the code via WireMock /token and validates via /jwks.json.
 *   No email / password / OTP interaction is needed.
 */
import { check } from "k6";
import { browser } from "k6/browser";
import exec from "k6/execution";

// Read the auth manifest generated by perf-tests/setup.ts.
// open() is evaluated once at init time — before any VUs start.
const manifest = JSON.parse(open("../tests/.session-cache/wiremock-auth-manifest.json"));
const workerUsers = manifest.workerUsers;

const targetUrl = __ENV.TARGET_URL ?? "http://localhost:3000";
// k6 runtime has no URL constructor — extract host with string ops instead.
const targetHost = targetUrl.replace(/^https?:\/\//, "").split("/")[0];
const headingTimeoutMs = 15000;

export const options = {
  scenarios: {
    ui: {
      executor: "shared-iterations",
      // Keep VU count <= workerUsers.length so each VU gets its own WireMock stub.
      vus: workerUsers.length,
      iterations: workerUsers.length,
      maxDuration: "5m",
      options: {
        browser: {
          type: "chromium",
        },
      },
    },
  },
  thresholds: {
    checks: ["rate>0.99"],
  },
};

export default async function () {
  // Assign each VU its own user to avoid auth-code collisions between VUs.
  const user = workerUsers[(exec.vu.idInTest - 1) % workerUsers.length];
  const loginHint = encodeURIComponent(user.nhsNumber ?? user.authContext.sub);

  const page = await browser.newPage();

  try {
    // 1) Navigate directly to /login?login_hint — WireMock handles the full OAuth exchange.
    //    The /authorize stub immediately 302s to /callback; no form interaction is required.
    const response = await page.goto(`${targetUrl}/login?login_hint=${loginHint}`, {
      waitUntil: "domcontentloaded",
    });

    check(response, {
      "navigation returned a response": (r) => r !== null,
      "response status is 2xx/3xx": (r) => r !== null && r.status() >= 200 && r.status() < 400,
    });

    // 2) Wait for the redirect chain to settle (login → WireMock → callback → app).
    await page.waitForURL(
      (url) => !url.pathname.includes("/login") && !url.pathname.includes("/callback"),
      { timeout: 30000 },
    );

    // 3) Validate the app loaded
    check(page.url(), {
      "ended up on app domain": (url) => url.includes(targetHost),
    });

    // 4) Check h1 exists and has text
    const heading = page.locator("h1");
    await heading.waitFor({ state: "visible", timeout: headingTimeoutMs });
    const headingText = await heading.textContent();

    check(headingText, {
      "page has visible non-empty h1": (text) => typeof text === "string" && text.trim().length > 0,
      "h1 is 'Get a self-test kit for HIV'": (text) => text === "Get a self-test kit for HIV",
    });
  } finally {
    await page.close();
  }
}
