sonar.projectKey=NHSDigital_hometest-service
sonar.organisation=nhsdigital

sonar.sourceEncoding=UTF-8

sonar.sources=lambdas/src,ui/src
sonar.tests=lambdas/src,ui/src

sonar.test.inclusions=**/*.test.ts,**/*.spec.ts,**/*.test.js,**/*.spec.js

sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/.next/**,**/build/**

sonar.typescript.tsconfigPaths=lambdas/tsconfig.json,ui/tsconfig.json

sonar.javascript.environments=node,browser
