import { Signer } from "@aws-sdk/rds-signer";
import {retrieveMandatoryEnvVariable, retrieveOptionalEnvVariable} from "../utils";

export interface ConnectionStringProvider {
  getConnectionString(): Promise<string>;
  getSslEnabled(): boolean;
  /**
   * When present, pg.Pool will call this function per new connection to obtain
   * a fresh password (e.g. an IAM auth token that expires after 15 minutes).
   */
  getDynamicPassword?: () => Promise<string>;
}

import type { SecretsClient } from "../secrets/secrets-manager-client";

export interface ConnectionConfig {
  username: string;
  address: string;
  port: string;
  database: string;
  schema?: string;
  passwordSecretName: string;
  ssl?: boolean;
}

export function postgresConnection(config: ConnectionConfig, secretsClient: SecretsClient): ConnectionStringProvider {
  let connectionStringPromise: Promise<string> | null = null;

  return {
    async getConnectionString(): Promise<string> {
      if (!connectionStringPromise) {
        connectionStringPromise = buildConnectionString(config, secretsClient);
      }
      return connectionStringPromise;
    },
    getSslEnabled(): boolean {
      return config.ssl !== false;
    }
  };
}

export function postgresFromEnv(secretsClient: SecretsClient): ConnectionStringProvider {
  if (retrieveOptionalEnvVariable("USE_IAM_AUTH") === "true") {
    return iamPostgresFromEnv();
  }

  const config: ConnectionConfig = {
    username: retrieveMandatoryEnvVariable("DB_USERNAME"),
    address: retrieveMandatoryEnvVariable("DB_ADDRESS"),
    port: retrieveMandatoryEnvVariable("DB_PORT"),
    database: retrieveMandatoryEnvVariable("DB_NAME"),
    schema: retrieveOptionalEnvVariable("DB_SCHEMA"),
    passwordSecretName: retrieveMandatoryEnvVariable("DB_SECRET_NAME"),
    ssl: retrieveOptionalEnvVariable("DB_SSL", "true") === "true"
  };

  return postgresConnection(config, secretsClient);
}

/**
 * Builds a ConnectionStringProvider that authenticates to Aurora using an IAM
 * auth token instead of a static password. The token is generated by the RDS
 * Signer using the Lambda's execution role credentials, is valid for 15 minutes,
 * and is refreshed automatically on every new pg.Pool connection.
 *
 * Requires:
 *  - Aurora cluster has IAM database authentication enabled
 *  - The DB user has been granted the rds_iam role in PostgreSQL
 *  - The Lambda execution role has rds-db:connect permission
 */
export function iamPostgresFromEnv(): ConnectionStringProvider {
  const username = retrieveMandatoryEnvVariable("DB_USERNAME");
  const address = retrieveMandatoryEnvVariable("DB_ADDRESS");
  const port = retrieveMandatoryEnvVariable("DB_PORT");
  const database = retrieveMandatoryEnvVariable("DB_NAME");
  const schema = retrieveOptionalEnvVariable("DB_SCHEMA");
  const region =
    retrieveOptionalEnvVariable("DB_REGION") ||
    process.env.AWS_REGION ||
    "eu-west-2";

  const signer = new Signer({
    region,
    hostname: address,
    port: parseInt(port, 10),
    username,
  });

  return {
    async getConnectionString(): Promise<string> {
      // Password is intentionally omitted — pg.Pool obtains it via getDynamicPassword
      const encodedUser = encodeURIComponent(username);
      const base = `postgresql://${encodedUser}@${address}:${port}/${database}`;
      const queryParams: string[] = ["sslmode=require"];
      if (schema) {
        queryParams.push(`options=${encodeURIComponent(`-c search_path=${schema}`)}`);
      }
      return `${base}?${queryParams.join("&")}`;
    },
    getSslEnabled(): boolean {
      return true;
    },
    async getDynamicPassword(): Promise<string> {
      return signer.getAuthToken();
    },
  };
}

async function buildConnectionString(
  config: ConnectionConfig,
  secretsClient: SecretsClient
): Promise<string> {
  const password = await secretsClient.getSecretValue(
    config.passwordSecretName,
    { jsonKey: "password" },
  );

  const username = encodeURIComponent(config.username);
  const sanitisedPassword = password.trim().replace(/^["']|["']$/g, '');
  const encodedPassword = encodeURIComponent(sanitisedPassword);
  const address = config.address;
  const port = config.port;
  const database = config.database;
  const base = `postgresql://${username}:${encodedPassword}@${address}:${port}/${database}`;

  const queryParams: string[] = [];

  if (config.schema) {
    const schemaOption = encodeURIComponent(`-c search_path=${config.schema}`);
    queryParams.push(`options=${schemaOption}`);
  }

  return queryParams.length > 0 ? `${base}?${queryParams.join('&')}` : base;
}
