WITH aggregated_data AS (
  SELECT 
    hc.id,
    hc.createdAt,
    hc.ageAtStart,
    hc.ageAtCompletion,
    hc.questionnaire_hasReceivedAnInvitation,
    hc.questionnaire_hasCompletedHealthCheckInLast5Years,
    hc.questionnaire_hasPreExistingCondition,
    hc.questionnaire_canCompleteHealthCheckOnline,
    hc.questionnaire_hasFamilyHeartAttackHistory,
    hc.questionnaire_hasFamilyDiabetesHistory,
    hc.questionnaire_sex,
    hc.questionnaire_ethnicBackground,
    hc.questionnaire_detailedEthnicGroup,
    hc.questionnaire_drinkAlcohol,
    hc.questionnaire_alcoholHowOften,
    hc.questionnaire_alcoholDailyUnits,
    hc.questionnaire_exerciseHours,
    hc.questionnaire_smoking,
    hc.questionnaire_bloodPressureDiastolic,
    hc.questionnaire_bloodPressureSystolic,
    hc.questionnaire_bloodPressureLocation,
    hc.questionnaire_healthCheckAccepted,
    hc.questionnaire_isAboutYouSectionSubmitted,
    hc.questionnaire_isAlcoholSectionSubmitted,
    hc.questionnaire_isBloodPressureSectionSubmitted,
    hc.questionnaire_isBodyMeasurementsSectionSubmitted,
    hc.questionnaire_isPhysicalActivitySectionSubmitted,
    hc.questionnaireScores_auditScore,
    hc.questionnaireScores_auditCategory,
    hc.questionnaireScores_activityCategory,
    hc.questionnaireScores_gppaqScore,
    hc.questionnaireScores_bmiScore,
    hc.questionnaireScores_bmiClassification,
    hc.questionnaireScores_bloodPressureCategory,
    hc.questionnaireScores_leicesterRiskScore,
    hc.questionnaireScores_leicesterRiskCategory,
    hc.questionnaireScores_smokingCategory,
    hc.questionnaireScores_townsendScore,
    hc.questionnaireScores_imd_decile,
    hc.questionnaireScores_imd_rank,
    hc.questionnaireScores_imd_score,
    hc.questionnaireCompletionDate,
    hc.riskScores_qRiskScore,
    hc.riskScores_qRiskScoreCategory,
    hc.riskScores_scoreCalculationDate,
    hc.riskScores_heartAge,
    hc.step,
    hc.bloodTestOrder_isBloodTestSectionSubmitted,
    hc.wasInvited,
    ARRAY_AGG(
      CAST(
        ROW(
          bs.date,
          bs.diabetes_overallCategory,
          bs.diabetes_diabetesCategory,
          bs.diabetes_diabetesFailureReason,
          bs.cholesterol_overallCategory,
          bs.cholesterol_hdlCholesterolCategory,
          bs.cholesterol_hdlCholesterolFailureReason,
          bs.cholesterol_totalCholesterolCategory,
          bs.cholesterol_totalCholesterolFailureReason,
          bs.cholesterol_totalCholesterolHdlRatioCategory,
          bs.cholesterol_totalCholesterolHdlRatioFailureReason
        ) AS ROW(
          biometricScore_date VARCHAR,
          diabetes_overallCategory VARCHAR,
          diabetes_diabetesCategory VARCHAR,
          diabetes_diabetesFailureReason VARCHAR,
          cholesterol_overallCategory VARCHAR,
          cholesterol_hdlCholesterolCategory VARCHAR,
          cholesterol_hdlCholesterolFailureReason VARCHAR,
          cholesterol_totalCholesterolCategory VARCHAR,
          cholesterol_totalCholesterolFailureReason VARCHAR,
          cholesterol_totalCholesterolHdlRatioCategory VARCHAR,
          cholesterol_totalCholesterolHdlRatioFailureReason VARCHAR
        )
      )
      ORDER BY bs.date ASC
    ) AS biometric_scores
  FROM 
    "{{databaseName}}"."{{flattenedHealthCheckViewName}}" hc
  LEFT JOIN 
    "{{databaseName}}"."{{flattenedBiometricScoreViewName}}" bs ON hc.id = bs.healthCheckId
  WHERE DATE_TRUNC('day', from_iso8601_timestamp(hc.createdAt)) >= DATE '{{goLiveDate}}'
  GROUP BY 
    hc.id,
    hc.createdAt,
    hc.ageAtStart,
    hc.ageAtCompletion,
    hc.questionnaire_hasReceivedAnInvitation,
    hc.questionnaire_hasCompletedHealthCheckInLast5Years,
    hc.questionnaire_hasPreExistingCondition,
    hc.questionnaire_canCompleteHealthCheckOnline,
    hc.questionnaire_hasFamilyHeartAttackHistory,
    hc.questionnaire_hasFamilyDiabetesHistory,
    hc.questionnaire_sex,
    hc.questionnaire_ethnicBackground,
    hc.questionnaire_detailedEthnicGroup,
    hc.questionnaire_drinkAlcohol,
    hc.questionnaire_alcoholHowOften,
    hc.questionnaire_alcoholDailyUnits,
    hc.questionnaire_exerciseHours,
    hc.questionnaire_smoking,
    hc.questionnaire_bloodPressureDiastolic,
    hc.questionnaire_bloodPressureSystolic,
    hc.questionnaire_bloodPressureLocation,
    hc.questionnaire_healthCheckAccepted,
    hc.questionnaire_isAboutYouSectionSubmitted,
    hc.questionnaire_isAlcoholSectionSubmitted,
    hc.questionnaire_isBloodPressureSectionSubmitted,
    hc.questionnaire_isBodyMeasurementsSectionSubmitted,
    hc.questionnaire_isPhysicalActivitySectionSubmitted,
    hc.questionnaireScores_auditScore,
    hc.questionnaireScores_auditCategory,
    hc.questionnaireScores_activityCategory,
    hc.questionnaireScores_gppaqScore,
    hc.questionnaireScores_bmiScore,
    hc.questionnaireScores_bmiClassification,
    hc.questionnaireScores_bloodPressureCategory,
    hc.questionnaireScores_leicesterRiskScore,
    hc.questionnaireScores_leicesterRiskCategory,
    hc.questionnaireScores_smokingCategory,
    hc.questionnaireScores_townsendScore,
    hc.questionnaireScores_imd_decile,
    hc.questionnaireScores_imd_rank,
    hc.questionnaireScores_imd_score,
    hc.questionnaireCompletionDate,
    hc.riskScores_qRiskScore,
    hc.riskScores_qRiskScoreCategory,
    hc.riskScores_scoreCalculationDate,
    hc.riskScores_heartAge,
    hc.step,
    hc.bloodTestOrder_isBloodTestSectionSubmitted,
    hc.wasInvited
) SELECT
  id,
  createdAt,
  ageAtStart,
  ageAtCompletion,
  questionnaire_hasReceivedAnInvitation,
  questionnaire_hasCompletedHealthCheckInLast5Years,
  questionnaire_hasPreExistingCondition,
  questionnaire_canCompleteHealthCheckOnline,
  questionnaire_hasFamilyHeartAttackHistory,
  questionnaire_hasFamilyDiabetesHistory,
  questionnaire_sex,
  questionnaire_ethnicBackground,
  questionnaire_detailedEthnicGroup,
  questionnaire_drinkAlcohol,
  questionnaire_alcoholHowOften,
  questionnaire_alcoholDailyUnits,
  questionnaire_exerciseHours,
  questionnaire_smoking,
  questionnaire_bloodPressureDiastolic,
  questionnaire_bloodPressureSystolic,
  questionnaire_bloodPressureLocation,
  questionnaire_healthCheckAccepted,
  questionnaire_isAboutYouSectionSubmitted,
  questionnaire_isAlcoholSectionSubmitted,
  questionnaire_isBloodPressureSectionSubmitted,
  questionnaire_isBodyMeasurementsSectionSubmitted,
  questionnaire_isPhysicalActivitySectionSubmitted,
  questionnaireScores_auditScore,
  questionnaireScores_auditCategory,
  questionnaireScores_activityCategory,
  questionnaireScores_gppaqScore,
  questionnaireScores_bmiScore,
  questionnaireScores_bmiClassification,
  questionnaireScores_bloodPressureCategory,
  questionnaireScores_leicesterRiskScore,
  questionnaireScores_leicesterRiskCategory,
  questionnaireScores_smokingCategory,
  questionnaireScores_townsendScore,
  questionnaireScores_imd_decile,
  questionnaireScores_imd_rank,
  questionnaireScores_imd_score,
  questionnaireCompletionDate,
  riskScores_qRiskScore,
  riskScores_qRiskScoreCategory,
  riskScores_scoreCalculationDate,
  riskScores_heartAge,
  step,
  bloodTestOrder_isBloodTestSectionSubmitted,
  wasInvited,
  biometric_scores[1].biometricScore_date AS biometricScore1_date,
  biometric_scores[1].diabetes_overallCategory AS diabetes1_overallCategory,
  biometric_scores[1].diabetes_diabetesCategory AS diabetes1_diabetesCategory,
  biometric_scores[1].diabetes_diabetesFailureReason AS diabetes1_diabetesFailureReason,
  biometric_scores[1].cholesterol_overallCategory AS cholesterol1_overallCategory,
  biometric_scores[1].cholesterol_hdlCholesterolCategory AS cholesterol1_hdlCholesterolCategory,
  biometric_scores[1].cholesterol_hdlCholesterolFailureReason AS cholesterol1_hdlCholesterolFailureReason,
  biometric_scores[1].cholesterol_totalCholesterolCategory AS cholesterol1_totalCholesterolCategory,
  biometric_scores[1].cholesterol_totalCholesterolFailureReason AS cholesterol1_totalCholesterolFailureReason,
  biometric_scores[1].cholesterol_totalCholesterolHdlRatioCategory AS cholesterol1_totalCholesterolHdlRatioCategory,
  biometric_scores[1].cholesterol_totalCholesterolHdlRatioFailureReason AS cholesterol1_totalCholesterolHdlRatioFailureReason,
  TRY(biometric_scores[2].biometricScore_date) AS biometricScore2_date,
  TRY(biometric_scores[2].diabetes_overallCategory) AS diabetes2_overallCategory,
  TRY(biometric_scores[2].diabetes_diabetesCategory) AS diabetes2_diabetesCategory,
  TRY(biometric_scores[2].diabetes_diabetesFailureReason) AS diabetes2_diabetesFailureReason,
  TRY(biometric_scores[2].cholesterol_overallCategory) AS cholesterol2_overallCategory,
  TRY(biometric_scores[2].cholesterol_hdlCholesterolCategory) AS cholesterol2_hdlCholesterolCategory,
  TRY(biometric_scores[2].cholesterol_hdlCholesterolFailureReason) AS cholesterol2_hdlCholesterolFailureReason,
  TRY(biometric_scores[2].cholesterol_totalCholesterolCategory) AS cholesterol2_totalCholesterolCategory,
  TRY(biometric_scores[2].cholesterol_totalCholesterolFailureReason) AS cholesterol2_totalCholesterolFailureReason,
  TRY(biometric_scores[2].cholesterol_totalCholesterolHdlRatioCategory) AS cholesterol2_totalCholesterolHdlRatioCategory,
  TRY(biometric_scores[2].cholesterol_totalCholesterolHdlRatioFailureReason) AS cholesterol2_totalCholesterolHdlRatioFailureReason
FROM 
  aggregated_data
ORDER BY createdAt ASC