SELECT
  id,
  healthCheckId,
  eventType,
  datetime,
  odsCode,
  source,
  nhcVersion,
  details_termsAndConditionsVersion,
  details_totalResults,
  details_filteredResults,
  details_bpTakenAt,
  details_writebackType,
  details_testTypes,
  details_reasons,
  details_followUp,
  details_notifyMessageID,
  details_page,
  details_healthCheckStep,
  details_expiryType,
  details_bpConfirmed,
  details_bpSymptoms,
  details_bpRoute,
  details_openedFrom,
  details_resourceTitle,
  details_bloodTestUpdatesMobileEntered,
  details_HbA1cStatus,
  details_lsoaVersion,
  details_imdVersion,
  details_cholesterolStatus,
  details_messageType,
  details_channel,
  details_journeySectionsComplete
FROM "{{databaseName}}"."{{flattenedAuditEventViewName}}"
WHERE DATE_TRUNC('day', from_iso8601_timestamp(datetime)) >= DATE '{{goLiveDate}}' 
ORDER BY datetime ASC