CREATE OR REPLACE VIEW "{{flattenedAuditEventViewName}}" AS
SELECT
  id,
  healthCheckId,
  eventType,
  datetime,
  patientId,
  odsCode,
  source,
  nhcVersion,
  hcDataModelVersion,
  details.termsAndConditionsVersion details_termsAndConditionsVersion,
  details.totalResults details_totalResults,
  details.filteredResults details_filteredResults,
  details.bpTakenAt details_bpTakenAt,
  details.writebackType details_writebackType,
  array_join(array_sort(details.testTypes), ', ') details_testTypes,
  array_join(array_sort(details.reasons), ', ') details_reasons,
  details.followUp details_followUp,
  details.notifyMessageID details_notifyMessageID,
  details.page details_page,
  details.healthCheckStep details_healthCheckStep,
  details.expiryType details_expiryType,
  details.bpConfirmed details_bpConfirmed,
  details.bpSymptoms details_bpSymptoms,
  details.bpRoute details_bpRoute,
  details.openedFrom details_openedFrom,
  details.resourceTitle details_resourceTitle,
  details.bloodTestUpdatesMobileEntered details_bloodTestUpdatesMobileEntered,
  details.previousDataModelVersion details_previousDataModelVersion,
  details.lsoaVersion details_lsoaVersion,
  details.imdVersion details_imdVersion,
  details.HbA1cStatus details_HbA1cStatus,
  details.cholesterolStatus details_cholesterolStatus,
  details.messageType details_messageType,
  details.channel details_channel,
  details.urlSource details_urlSource,
  array_join(array_sort(details.journeySectionsComplete), ', ') details_journeySectionsComplete
FROM "{{auditEventTableName}}";