export enum EnvironmentVariables {
  ENV = 'ENV',
  UI_BASE_URL = 'UI_BASE_URL',
  UI_ORDER_JOURNEY_URL = 'UI_ORDER_JOURNEY_URL',
  API_BASE_URL = 'API_BASE_URL',
  HEADLESS = 'HEADLESS',
  TIMEOUT = 'TIMEOUT',
  SLOW_MO = 'SLOW_MO',
  ACCESSIBILITY_STANDARDS = 'ACCESSIBILITY_STANDARDS',
  REPORTING_OUTPUT_DIRECTORY = 'REPORTING_OUTPUT_DIRECTORY',
  EXTERNAL_LINK_SEXUAL_HEALTH_CLINIC = 'EXTERNAL_LINK_SEXUAL_HEALTH_CLINIC',
  EXTERNAL_LINK_NEAREST_AE = 'EXTERNAL_LINK_NEAREST_AE',
  EXTERNAL_LINK_HIV_AIDS_INFO = 'EXTERNAL_LINK_HIV_AIDS_INFO',
}

export const availableEnvironments = ['local','dev'] as const;
export type Environment = typeof availableEnvironments[number];
