export enum EnvironmentVariables {
  ENV = "ENV",
  UI_BASE_URL = "UI_BASE_URL",
  UI_ORDER_JOURNEY_URL = "UI_ORDER_JOURNEY_URL",
  API_BASE_URL = "API_BASE_URL",
  HEADLESS = "HEADLESS",
  TIMEOUT = "TIMEOUT",
  SLOW_MO = "SLOW_MO",
  ACCESSIBILITY_STANDARDS = "ACCESSIBILITY_STANDARDS",
  REPORTING_OUTPUT_DIRECTORY = "REPORTING_OUTPUT_DIRECTORY",
  DB_HOST = "DB_HOST",
  DB_PORT = "DB_PORT",
  DB_NAME = "DB_NAME",
  DB_USER = "DB_USER",
  DB_PASSWORD = "DB_PASSWORD",
  DB_SCHEMA = "DB_SCHEMA",
  AUTH_TYPE = "AUTH_TYPE",
  WIREMOCK_BASE_URL = "WIREMOCK_BASE_URL",
  CHROMIUM_ONLY = "CHROMIUM_ONLY",
}

export const availableEnvironments = ["local", "dev"] as const;
export type Environment = (typeof availableEnvironments)[number];
