---
name: "Perform pre-commit checks"
description: "Perform pre-commit checks"
runs:
  using: "composite"
  steps:
    - name: Install pre-commit dependencies
      working-directory: /tmp
      shell: bash
      run: |
        sudo curl -fsSL https://mise.jdx.dev/gpg-key.pub | sudo gpg --dearmor -o /etc/apt/keyrings/mise-archive-keyring.gpg
        sudo echo "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.gpg arch=amd64] https://mise.jdx.dev/deb stable main" | sudo tee /etc/apt/sources.list.d/mise.list
        sudo apt-get update
        sudo apt-get install -y mise

    - name: Install pre-commit
      shell: bash
      run: |
        git config --global --add safe.directory '*'
        pre-commit install --install-hooks

    - name: Run pre-commit
      shell: bash
      run: |
        pre-commit run --all-files --show-diff-on-failure --color=always
      env:
        PRE_COMMIT_COLOR: always
