import {HttpClient} from "../../lambdas/src/lib/http/http-client";
import {Service} from "../../lambdas/src/lib/service";
import {Commons} from "../../lambdas/src/lib/commons";

export interface LaLookupResult {
  localAuthorityCode: string;
  region: string;
}

export interface LaLookupServiceProperties {
  httpClient: HttpClient;
  baseUrl: string;
}

export class LaLookupService extends Service {
  private readonly baseUrl: string;
  private readonly httpClient: HttpClient

  constructor(
    {baseUrl, httpClient}: LaLookupServiceProperties,
    commons: Commons
  ) {
    super('LALookupService', commons);
    this.baseUrl = baseUrl;
    this.httpClient = httpClient;
  }

  async lookupByPostcode(postcode: string): Promise<LaLookupResult | null> {
    try {
      // define something correct here
      const data = await this.httpClient.get<any>(`${this.baseUrl}/la?postcode=${postcode}`);

      if (!data || !data.result) return null;

      // some generic object generated by AI as a placeholder to be updated
      return {
        localAuthorityCode: data.result.codes.admin_district,
        region: data.result.region || data.result.nhs_ha,
      };
    } catch (error) {
      this.logger.error(`Local Authority lookup failed`, {postcode, error});
      return null;
    }
  }
}
