import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const AWS_RDS_CERT_URL =
  "https://truststore.pki.rds.amazonaws.com/eu-west-2/eu-west-2-bundle.pem";
const OUTPUT_PATH = join(__dirname, "../src/certs/eu-west-2-bundle.ts");

async function fetchCert(url: string): Promise<string> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch certificate: ${response.status} ${response.statusText}`);
  }
  return response.text();
}

function readExistingCert(path: string): string | null {
  if (!existsSync(path)) return null;
  const match = readFileSync(path, "utf-8").match(/export const EU_WEST_2_BUNDLE = (.*);/s);
  return match ? JSON.parse(match[1]) : null;
}


async function main() {
  console.log("Fetching RDS certificate bundle...");
  const cert = await fetchCert(AWS_RDS_CERT_URL);

  const existingCert = readExistingCert(OUTPUT_PATH);
  if (existingCert === cert) {
    console.log("Certificate is unchanged, skipping update.");
    return;
  }

  const output = `// Auto-generated by scripts/update-rds-cert.ts
// Source: ${AWS_RDS_CERT_URL}
// Updated: ${new Date().toISOString()}
// Do not edit manually — run: npm run update-rds-cert
// This is a public certificate bundle, so it's safe to commit it to version control.

export const EU_WEST_2_BUNDLE = ${JSON.stringify(cert)};
`;

  writeFileSync(OUTPUT_PATH, output, "utf-8");
  console.log(`Certificate written to ${OUTPUT_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
