---
services:
    localstack:
        image: localstack/localstack:latest
        container_name: localstack-main
        ports:
            - 127.0.0.1:4566:4566        # LocalStack Gateway
            - 127.0.0.1:4510-4559:4510-4559 # external services port range
        environment:
            - SERVICES=lambda,iam,logs,s3,cloudformation,sts,apigateway,ssm
            - DEBUG=1
            - LAMBDA_EXECUTOR=docker
            - AWS_DEFAULT_REGION=eu-west-1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./localstack-data:/var/lib/localstack
            - ./scripts/localstack/:/etc/scripts/
            - ./scripts/localstack/deploy.sh:/etc/localstack/init/ready.d/deploy.sh
    ui:
        image: node:24
        container_name: ui
        working_dir: /app
        volumes:
            - ../ui:/app
            - ui_node_modules:/app/node_modules
        command: sh -c "npm install && npm run dev"
        ports:
            - 3000:3000
        environment:
            - REACT_APP_API_URL=http://localstack:4566
        depends_on:
            - localstack
    postgres-db:
        image: postgres:18.1
        container_name: postgres-db
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=mydb
        ports:
            - 5432:5432
        volumes:
            - ./db-data:/var/lib/postgresql

volumes:
    ui_node_modules:
