# Organization and project keys are displayed in the right sidebar of the project homepage
sonar.organization=nhsdigital
sonar.projectKey=nhsdigital_digital-health-checks-infra-backend
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=__tests__
sonar.cpd.exclusions=__tests__
sonar.exclusions=__tests__/**/*
sonar.coverage.exclusions=src/**/index.ts,src/**/init.ts,src/nhc-email-verification-stack/**,src/nhc-mocks-stack/**,src/lib/mock/**,src/lib/http/security-headers.ts,src/lib/emis/request-templates/FileRecordExample.ts,src/lib/logging/nhc-log-formatter.ts,src/lib/http/security-headers.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info