export enum SpecialUserKey {
  ELIGIBLE_USER = 'ELIGIBLE_USER',
  ELIGIBLE_USER_2 = 'ELIGIBLE_USER_2',
  LOGOUT_DEDICATED_USER = 'LOGOUT_DEDICATED_USER',
  ELIGIBLE_E2E_DEDICATED_USER = 'ELIGIBLE_E2E_DEDICATED_USER',
  CONSENT_NOT_GIVEN = 'CONSENT_NOT_GIVEN',
  INELIGIBLE_USER_OVERAGE_BOUNDARY = 'INELIGIBLE_USER_OVERAGE_BOUNDARY',
  INELIGIBLE_USER_UNDERAGE_BOUNDARY = 'INELIGIBLE_USER_UNDERAGE_BOUNDARY',
  NOT_WHITELISTED_NHS_NUMBER = 'NOT_WHITELISTED_NHS_NUMBER',
  INELIGIBLE_INVALID_PROOFING_LEVEL = 'INELIGIBLE_INVALID_PROOFING_LEVEL',
  INELIGIBLE_SUB_CLAIM_NOT_MATCH = 'INELIGIBLE_SUB_CLAIM_NOT_MATCH',
  INELIGIBLE_TOKEN_FAILURE = 'INELIGIBLE_TOKEN_FAILURE',
  INELIGIBLE_SSO_ERROR = 'INELIGIBLE_SSO_ERROR',
  INELIGIBLE_USERINFO_FAILURE = 'INELIGIBLE_USERINFO_FAILURE',
  INELIGIBLE_ODS_CODE_DISABLED_USER = 'INELIGIBLE_ODS_CODE_DISABLED_USER',
  PATIENT_FOR_LOGOUT_API_TEST = 'PATIENT_FOR_LOGOUT_API_TEST'
}
