sonar.organization=nhsdigital
sonar.projectKey=nhsdigital_digital-health-checks
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=src/__tests__
sonar.inclusions=src/**/*
sonar.exclusions=src/__tests__/**/*,src/env/**/*
sonar.cpd.exclusions=src/__tests__/**/*
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/lib/components/__mocks__/event-audit-button.tsx, src/layouts/MainLayout.tsx, src/scripts/prepare-static-pages.js, src/lib/components/session-timer/utils.tsx
