name: Deploy APIM proxy for Sandbox
run-name: Publish ${{ github.ref_name }} by @${{ github.actor }} (${{ github.sha }} - ${{ github.event.head_commit.message }})
on:
  workflow_dispatch:

jobs:
  release_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}

      - name: Prepare python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 24

      - name: Install dependencies
        run: |
          npm ci
          pipx install proxygen-cli

      - name: Setup proxygen-cli
        env:
          PROXYGEN_PRIVATE_KEY: ${{ secrets.PROXYGEN_PRIVATE_KEY }}
          PROXYGEN_KID: ${{ secrets.PROXYGEN_KID }}
          PROXYGEN_CLIENT_ID: ${{ secrets.PROXYGEN_CLIENT_ID }}
        run: |
          # Setup proxygen auth and settings
          mkdir -p ${HOME}/.proxygen
          echo "$PROXYGEN_PRIVATE_KEY" > ${HOME}/.proxygen/key
          envsubst < ./apim/proxygen-credentials-template.yaml > ${HOME}/.proxygen/credentials.yaml
          envsubst < ./apim/proxygen-settings.yaml > ${HOME}/.proxygen/settings.yaml
          proxygen status

      - name: Authenticate with docker registry
        run: $(proxygen docker get-login)

      - name: Build docker image for sandbox
        run: docker build --platform linux/amd64 -t home-testing-sandbox:1.0.0 sandbox/

      - name: Tag docker image
        run: docker image tag home-testing-sandbox:1.0.0 $(proxygen docker registry)/home-testing:latest

      - name: Push docker image to registry
        run: docker push $(proxygen docker registry)/home-testing:latest

      - name: Publish spec
        run: npm run deploy-apim sandbox home-testing

      - name: Retrieve spec
        run: proxygen instance get sandbox home-testing
