name: Deploy APIM proxy for Int (internal-qa APIM env)
run-name: Deploy APIM proxy for Int / internal-qa - ${{ inputs.ref }}

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch or tag to deploy"
        required: true
        default: ""

jobs:
  deploy-apim-job:
    name: Deploy APIM for Int Environment (Internal QA APIM env)
    uses: ./.github/workflows/apim-deploy.yml
    with:
      ref: ${{ inputs.ref }}
      apim-env: internal-qa
      account: int
    secrets: inherit
