---
name: "CI/CD pull request"

# The total recommended execution time for the "CI/CD Pull Request" workflow is around 20 minutes.

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  metadata:
    name: "Set CI/CD metadata"
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      build_datetime: ${{ steps.variables.outputs.build_datetime }}
      build_timestamp: ${{ steps.variables.outputs.build_timestamp }}
      nodejs_version: ${{ steps.variables.outputs.nodejs_version }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v6
      - name: "Set CI/CD variables"
        id: variables
        run: |
          datetime=$(date -u +'%Y-%m-%dT%H:%M:%S%z')
          echo "build_datetime=$datetime" >> $GITHUB_OUTPUT
          echo "build_timestamp=$(date --date=$datetime -u +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
          echo "nodejs_version=$(grep "^v" .nvmrc | cut -f2 -d'v')" >> $GITHUB_OUTPUT
      - name: "List variables"
        env:
          BUILD_DATETIME: ${{ steps.variables.outputs.build_datetime }}
          BUILD_TIMESTAMP: ${{ steps.variables.outputs.build_timestamp }}
          NODEJS_VERSION: ${{ steps.variables.outputs.nodejs_version }}
        run: |
          export BUILD_DATETIME
          export BUILD_TIMESTAMP
          export NODEJS_VERSION
          make list-variables
  commit-stage: # Recommended maximum execution time is 2 minutes
    name: "Commit stage"
    needs: [metadata]
    uses: ./.github/workflows/stage-1-commit.yaml
    with:
      build_datetime: "${{ needs.metadata.outputs.build_datetime }}"
      build_timestamp: "${{ needs.metadata.outputs.build_timestamp }}"
      run_pre_commit: ${{ github.event_name == 'pull_request' }}
      pre_commit_base_sha: "${{ github.event.pull_request.base.sha || '' }}"
    secrets: inherit
  test-stage: # Recommended maximum execution time is 5 minutes
    name: "Test stage"
    needs: [metadata, commit-stage]
    uses: ./.github/workflows/stage-2-test.yaml
    with:
      build_datetime: "${{ needs.metadata.outputs.build_datetime }}"
      build_timestamp: "${{ needs.metadata.outputs.build_timestamp }}"
      nodejs_version: "${{ needs.metadata.outputs.nodejs_version }}"
    secrets: inherit
