name: Deploy to Int (Int)
run-name: Deploy - int - ${{ inputs.ref }}

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to deploy'
        required: true
        default: ''
      run-tests:
        description: 'Run regression tests'
        required: false
        type: boolean
        default: true

jobs:
  deploy-int-job:
    name: Deploy Int Environment
    uses: ./.github/workflows/deploy.yml
    with:
      ref: ${{ inputs.ref }}
      env: int
      account: int
    secrets: inherit

  run-regression-tests:
    name: Run Automated Regression Tests on Ubuntu and Chromium
    needs: deploy-int-job
    if: ${{ inputs.run-tests }}
    uses: ./.github/workflows/run-regression-tests.yml
    with:
      environment: int
      account: int
      os: 'ubuntu-latest'
      browser: 'chromium'
      testsToCover: 'All'
    secrets: inherit
