name: Run action on Prod
run-name: Run action on Prod - Prod - ${{ inputs.tag}} - ${{inputs.jobType}}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        type: string
        default: ''
      jobType:
        description: 'Type of release job (pre-release or post-release)'
        required: true
        type: choice
        options:
          - pre-release
          - post-release
        default: 'pre-release'
      dryRun:
        description: 'Run in dry-run mode (true or false)'
        required: true
        type: boolean
        default: true
      backupHealthCheckTable:
        description: 'Backup Health Check table before migration'
        required: true
        type: boolean
        default: false

jobs:
  run-action:
    name: Prod Environment Release Migration
    uses: ./.github/workflows/run-action.yml
    with:
      env: prod
      tag: ${{ inputs.tag }}
      jobType: ${{ inputs.jobType }}
      dryRun: ${{ inputs.dryRun }}
      account: prod
      backupHealthCheckTable: ${{ inputs.backupHealthCheckTable }}
    secrets: inherit
