// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { order_uid } from './TestOrder';

/** Identifier type for consent */
export type consent_uid = string;

/** Represents the table hometest.consent */
export default interface Consent {
  consentUid: consent_uid;

  orderUid: order_uid;

  createdAt: Date;
}

/** Represents the initializer for the table hometest.consent */
export interface ConsentInitializer {
  consentUid?: consent_uid;

  orderUid: order_uid;

  createdAt?: Date;
}

/** Represents the mutator for the table hometest.consent */
export interface ConsentMutator {
  consentUid?: consent_uid;

  orderUid?: order_uid;

  createdAt?: Date;
}
