// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for goose_db_version */
export type id = string;

/** Represents the table hometest.goose_db_version */
export default interface GooseDbVersion {
  id: id;

  version_id: string;

  is_applied: boolean;

  tstamp: Date;
}

/** Represents the initializer for the table hometest.goose_db_version */
export interface GooseDbVersionInitializer {
  id?: id;

  version_id: string;

  is_applied: boolean;

  /** Default value: now() */
  tstamp?: Date;
}

/** Represents the mutator for the table hometest.goose_db_version */
export interface GooseDbVersionMutator {
  id?: id;

  version_id?: string;

  is_applied?: boolean;

  tstamp?: Date;
}
