// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { supplier_id } from './Supplier';
import type { test_code } from './TestType';

/** Identifier type for la_supplier_offering */
export type offering_id = string;

/** Represents the table hometest.la_supplier_offering */
export default interface LaSupplierOffering {
  offeringId: offering_id;

  supplierId: supplier_id | null;

  testCode: test_code | null;

  laCode: string;

  effectiveFrom: Date | null;
}

/** Represents the initializer for the table hometest.la_supplier_offering */
export interface LaSupplierOfferingInitializer {
  offeringId?: offering_id;

  supplierId?: supplier_id | null;

  testCode?: test_code | null;

  laCode: string;

  effectiveFrom?: Date | null;
}

/** Represents the mutator for the table hometest.la_supplier_offering */
export interface LaSupplierOfferingMutator {
  offeringId?: offering_id;

  supplierId?: supplier_id | null;

  testCode?: test_code | null;

  laCode?: string;

  effectiveFrom?: Date | null;
}
