// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { supplier_id } from './Supplier';
import type { test_code } from './TestType';

/** Identifier type for la_supplier_offering */
export type offering_id = string;

/** Represents the table hometest.la_supplier_offering */
export default interface LaSupplierOffering {
  offering_id: offering_id;

  supplier_id: supplier_id | null;

  test_code: test_code | null;

  la_code: string;

  effective_from: Date | null;
}

/** Represents the initializer for the table hometest.la_supplier_offering */
export interface LaSupplierOfferingInitializer {
  /** Default value: gen_random_uuid() */
  offering_id?: offering_id;

  supplier_id?: supplier_id | null;

  test_code?: test_code | null;

  la_code: string;

  /** Default value: CURRENT_TIMESTAMP */
  effective_from?: Date | null;
}

/** Represents the mutator for the table hometest.la_supplier_offering */
export interface LaSupplierOfferingMutator {
  offering_id?: offering_id;

  supplier_id?: supplier_id | null;

  test_code?: test_code | null;

  la_code?: string;

  effective_from?: Date | null;
}
