// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { order_uid } from './TestOrder';
import type { status_code } from './StatusType';

/** Identifier type for order_status */
export type status_id = string;

/** Represents the table hometest.order_status */
export default interface OrderStatus {
  statusId: status_id;

  orderUid: order_uid;

  orderReference: string | null;

  statusCode: status_code;

  createdAt: Date | null;

  correlationId: string;
}

/** Represents the initializer for the table hometest.order_status */
export interface OrderStatusInitializer {
  statusId?: status_id;

  orderUid: order_uid;

  orderReference?: string | null;

  statusCode: status_code;

  createdAt?: Date | null;

  correlationId?: string;
}

/** Represents the mutator for the table hometest.order_status */
export interface OrderStatusMutator {
  statusId?: status_id;

  orderUid?: order_uid;

  orderReference?: string | null;

  statusCode?: status_code;

  createdAt?: Date | null;

  correlationId?: string;
}
