// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { order_uid } from './TestOrder';
import type { status_code } from './StatusType';

/** Identifier type for order_status */
export type status_id = string;

/** Represents the table hometest.order_status */
export default interface OrderStatus {
  status_id: status_id;

  order_uid: order_uid;

  order_reference: string | null;

  status_code: status_code;

  created_at: Date | null;

  correlation_id: string;
}

/** Represents the initializer for the table hometest.order_status */
export interface OrderStatusInitializer {
  /** Default value: gen_random_uuid() */
  status_id?: status_id;

  order_uid: order_uid;

  order_reference?: string | null;

  status_code: status_code;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  /** Default value: gen_random_uuid() */
  correlation_id?: string;
}

/** Represents the mutator for the table hometest.order_status */
export interface OrderStatusMutator {
  status_id?: status_id;

  order_uid?: order_uid;

  order_reference?: string | null;

  status_code?: status_code;

  created_at?: Date | null;

  correlation_id?: string;
}
