// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for patient_mapping */
export type patient_uid = string;

/** Represents the table hometest.patient_mapping */
export default interface PatientMapping {
  patientUid: patient_uid;

  nhsNumber: string | null;

  birthDate: Date;
}

/** Represents the initializer for the table hometest.patient_mapping */
export interface PatientMappingInitializer {
  patientUid?: patient_uid;

  nhsNumber?: string | null;

  birthDate: Date;
}

/** Represents the mutator for the table hometest.patient_mapping */
export interface PatientMappingMutator {
  patientUid?: patient_uid;

  nhsNumber?: string | null;

  birthDate?: Date;
}
