// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { order_uid } from './TestOrder';
import type { result_code } from './ResultType';

/** Identifier type for result_status */
export type result_id = string;

/** Represents the table hometest.result_status */
export default interface ResultStatus {
  resultId: result_id;

  orderUid: order_uid;

  status: result_code;

  createdAt: Date | null;

  correlationId: string;
}

/** Represents the initializer for the table hometest.result_status */
export interface ResultStatusInitializer {
  orderUid: order_uid;

  status: result_code;

  createdAt?: Date | null;

  correlationId: string;
}

/** Represents the mutator for the table hometest.result_status */
export interface ResultStatusMutator {
  orderUid?: order_uid;

  status?: result_code;

  createdAt?: Date | null;

  correlationId?: string;
}
