// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for result_type */
export type result_code = string;

/** Represents the table hometest.result_type */
export default interface ResultType {
  result_code: result_code;

  description: string;
}

/** Represents the initializer for the table hometest.result_type */
export interface ResultTypeInitializer {
  result_code: result_code;

  description: string;
}

/** Represents the mutator for the table hometest.result_type */
export interface ResultTypeMutator {
  result_code?: result_code;

  description?: string;
}
