// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { order_uid } from './TestOrder';
import type { result_code } from './ResultType';

/** Identifier type for result_status */
export type result_id = string;

/** Represents the table hometest.result_status */
export default interface ResultStatus {
  result_id: result_id;

  order_uid: order_uid;

  status: result_code;

  created_at: Date | null;

  correlation_id: string;
}

/** Represents the initializer for the table hometest.result_status */
export interface ResultStatusInitializer {
  order_uid: order_uid;

  status: result_code;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;

  correlation_id: string;
}

/** Represents the mutator for the table hometest.result_status */
export interface ResultStatusMutator {
  order_uid?: order_uid;

  status?: result_code;

  created_at?: Date | null;

  correlation_id?: string;
}
