// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for status_type */
export type status_code = string;

/** Represents the table hometest.status_type */
export default interface StatusType {
  statusCode: status_code;

  description: string;
}

/** Represents the initializer for the table hometest.status_type */
export interface StatusTypeInitializer {
  statusCode: status_code;

  description: string;
}

/** Represents the mutator for the table hometest.status_type */
export interface StatusTypeMutator {
  statusCode?: status_code;

  description?: string;
}
