// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for supplier */
export type supplier_id = string;

/** Represents the table hometest.supplier */
export default interface Supplier {
  supplierId: supplier_id;

  supplierName: string;

  serviceUrl: string;

  websiteUrl: string | null;

  clientSecretName: string;

  clientId: string;

  oauthTokenPath: string | null;

  orderPath: string | null;

  oauthScope: string | null;

  resultsPath: string | null;
}

/** Represents the initializer for the table hometest.supplier */
export interface SupplierInitializer {
  supplierId?: supplier_id;

  supplierName: string;

  serviceUrl: string;

  websiteUrl?: string | null;

  clientSecretName: string;

  clientId: string;

  oauthTokenPath?: string | null;

  orderPath?: string | null;

  oauthScope?: string | null;

  resultsPath?: string | null;
}

/** Represents the mutator for the table hometest.supplier */
export interface SupplierMutator {
  supplierId?: supplier_id;

  supplierName?: string;

  serviceUrl?: string;

  websiteUrl?: string | null;

  clientSecretName?: string;

  clientId?: string;

  oauthTokenPath?: string | null;

  orderPath?: string | null;

  oauthScope?: string | null;

  resultsPath?: string | null;
}
