// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for supplier */
export type supplier_id = string;

/** Represents the table hometest.supplier */
export default interface Supplier {
  supplier_id: supplier_id;

  supplier_name: string;

  service_url: string;

  website_url: string | null;

  client_secret_name: string;

  client_id: string;

  oauth_token_path: string | null;

  order_path: string | null;

  oauth_scope: string | null;

  results_path: string | null;
}

/** Represents the initializer for the table hometest.supplier */
export interface SupplierInitializer {
  /** Default value: gen_random_uuid() */
  supplier_id?: supplier_id;

  supplier_name: string;

  service_url: string;

  website_url?: string | null;

  client_secret_name: string;

  client_id: string;

  oauth_token_path?: string | null;

  order_path?: string | null;

  oauth_scope?: string | null;

  results_path?: string | null;
}

/** Represents the mutator for the table hometest.supplier */
export interface SupplierMutator {
  supplier_id?: supplier_id;

  supplier_name?: string;

  service_url?: string;

  website_url?: string | null;

  client_secret_name?: string;

  client_id?: string;

  oauth_token_path?: string | null;

  order_path?: string | null;

  oauth_scope?: string | null;

  results_path?: string | null;
}
