// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { supplier_id } from './Supplier';
import type { patient_uid } from './PatientMapping';
import type { test_code } from './TestType';

/** Identifier type for test_order */
export type order_uid = string;

/** Represents the table hometest.test_order */
export default interface TestOrder {
  order_uid: order_uid;

  order_reference: string;

  supplier_id: supplier_id;

  patient_uid: patient_uid;

  test_code: test_code;

  originator: string | null;

  created_at: Date | null;
}

/** Represents the initializer for the table hometest.test_order */
export interface TestOrderInitializer {
  /** Default value: gen_random_uuid() */
  order_uid?: order_uid;

  supplier_id: supplier_id;

  patient_uid: patient_uid;

  test_code: test_code;

  originator?: string | null;

  /** Default value: CURRENT_TIMESTAMP */
  created_at?: Date | null;
}

/** Represents the mutator for the table hometest.test_order */
export interface TestOrderMutator {
  order_uid?: order_uid;

  supplier_id?: supplier_id;

  patient_uid?: patient_uid;

  test_code?: test_code;

  originator?: string | null;

  created_at?: Date | null;
}
