// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for test_type */
export type test_code = string;

/** Represents the table hometest.test_type */
export default interface TestType {
  test_code: test_code;

  description: string;
}

/** Represents the initializer for the table hometest.test_type */
export interface TestTypeInitializer {
  test_code: test_code;

  description: string;
}

/** Represents the mutator for the table hometest.test_type */
export interface TestTypeMutator {
  test_code?: test_code;

  description?: string;
}
