// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { supplier_id } from './Supplier';
import type { patient_uid } from './PatientMapping';
import type { test_code } from './TestType';

/** Identifier type for test_order */
export type order_uid = string;

/** Represents the table hometest.test_order */
export default interface TestOrder {
  orderUid: order_uid;

  orderReference: string;

  supplierId: supplier_id;

  patientUid: patient_uid;

  testCode: test_code;

  originator: string | null;

  createdAt: Date | null;
}

/** Represents the initializer for the table hometest.test_order */
export interface TestOrderInitializer {
  orderUid?: order_uid;

  supplierId: supplier_id;

  patientUid: patient_uid;

  testCode: test_code;

  originator?: string | null;

  createdAt?: Date | null;
}

/** Represents the mutator for the table hometest.test_order */
export interface TestOrderMutator {
  orderUid?: order_uid;

  supplierId?: supplier_id;

  patientUid?: patient_uid;

  testCode?: test_code;

  originator?: string | null;

  createdAt?: Date | null;
}
